FROM tensorflow/tensorflow:1.12.3-py3

LABEL maintainer="jonathanstaniforth@gmail.com"

WORKDIR /tf/neurec

COPY ./neurec .

COPY . .

RUN pip3 install neurec && \
    pip3 install -r requirements.txt

WORKDIR /tf

EXPOSE 8888
